### ISSUE TITLE
Bug in plotplm

### ISSUE THREAD

**Issue by harig00** [csdms-contrib/slepian_alpha#18]
There is a bug in plotplm.

`load topo; topo=flipud(topo); plotplm(topo,[],[],6)
`
 This should result in a plot of the data over the south pole. The data is correctly plotted as from the south pole, however the coastlines are shown for the north pole. Also the graph is not aligned with 0 degree lon up. It appears that the view is somehow set to an oblique viewpoint.

**Comment by fjsimons** [comment]
OK, I finally resolved this. Not elegant, pretty or universal, but at least it does produce a nice plot.
