### ISSUE TITLE
function penlift.m

### ISSUE THREAD

**Issue by projetM220212022** [csdms-contrib/slepian_alpha#20]
hello, 
How can I replace the function "insert" in "penlift.m" ? Because I don't have Database Toolbox.
Thank you for your answer.

**Comment by fjsimons** [comment]
Hi, the function "insert.m" is ALSO one that is in the **slepian_alpha** toolbox. There should be no need for the Database Toolbox. It was written before that toolbox even existed. I'm not sure why your system would be confused that it thinks it may need it.
