### ISSUE TITLE
How does one get the data files?

### ISSUE THREAD

**Issue by gradywright** [csdms-contrib/slepian_alpha#4]
I set the environment variable `$IFILES` as indicated in the README file, and even created a directory called COASTS where `$IFILES` points.  However, when I try `localization('demo1')`, I get an error related to the fact that the file `cont.mtl` can't be found. 

In general many of the demo file seem to assume that some data files are present on the system.  How does one go about getting these files?  Is it possible to include these with the distribution of the code?

**Comment by fjsimons** [comment]
Hi Grady, these missing files are still on my software page, at the bottom. They should and will be moved over to the GitHub site! http://geoweb.princeton.edu/people/simons/software.html

**Comment by gradywright** [comment]
Thanks for the quick response @fjsimons.  I worked my way through the code and downloaded the files needed to run some of the demos.  The software is really nice.

On a related note, I recently discovered the useful `matlab`command `websave` that allows one to download files directly from the internet.  Rather than putting all the data files on github, you could use this command to download them from your website to the correct directory on the users computer.  For example,
```
filename = fullfile(getenv('IFILES'),'EARTHMODELS','CONSTANTS','SHM.mat')
websave(filename,'http://geoweb.princeton.edu/people/simons/DOTM/SHM.mat')
```
Will download `SHM.mat` from your website and save it in the correct directory (assuming that the directories have been created.
