### ISSUE TITLE
IFILES/KERNELC vs IFILES/KERNELCP

### ISSUE THREAD

**Issue by AlainPlattner** [csdms-contrib/slepian_alpha#5]
I suggest to have both kernelc and kernelcp save their files into IFILES/KERNELC. instead of two different folders (the files are the same).

**Comment by harig00** [comment]
Yes, this is on the eventual to-do list. Do you want to do it, or should I?

Need to 1) check the save names in both files to make sure they are creating files which can be read/loaded by either file, and then 2) put in a TRY CATCH statement in kernelcp to look in the old directory first before doing the regular directory (basically backwards compatibility).

**Comment by harig00** [comment]
I made these changes in kernelcp. A little convoluted to preserve backwards compatibility. Take and look and if you like it just close this issue.
